### ISSUE TITLE
Increase avatar size on forum posts for non-mobile viewing

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#147]
According to Inspect Element on Chrome, avatars on forum posts are displaying at 41px x 41px. Can we increase this to 60px x 60px for non-mobile users? The current size of avatars on the mobile site is great, IMO, but they're too small on PC browsers.

Keep the current avatar size on blog comments, profile pages, activity feeds, guides, guide comments, dev tracker/sidebar posts, influence posts and influence comments. This is ONLY for avatars on forum thread posts.

**Comment by iamjohnp** [comment]
@iamisom are you getting complaints from users on this? I personally think the current size is great since the content should really be what draws attention on the page. I understand that avatars are a nice expression of personality, but would rather avoid cluttering up the page if it can be avoided.

Let me know and we can get this implemented if it's high prio.

**Comment by iamisom** [comment]
https://www.dungeondefenders.com/2/topic/116404/improvement-avatar-size

Our old Website Feedback threads were wiped, but it was a fairly common comment. I personally think they should be a bit larger because they're a tiny bit too small. While focusing on content is great, people associate forum posters with their avatars. Our current forums decrease this association and loses some of the personal identification bond forming that I love on forums.

**Comment by iamjohnp** [comment]
makes sense. we'll get this in queue and busted out right quick!

**Comment by iamjohnp** [comment]
@mbizzle can you take a quick swipe at this? please note that this is only in forums, as josh outlined above. let me know if you have questions...

**Comment by iamjohnp** [comment]
@mbizzle can we get equal padding around the entire avatar?

![](http://ss.imjp.me/20150128092034.png)

right now it's basically touching the username and badge. feels too squishy.

**Comment by iamjohnp** [comment]
meanwhile, @iamisom can you just double check that screenshot above and let me know if that feels about right to you, size-wise?

**Comment by iamisom** [comment]
I'm curious:  Is it possible to increase the avatar size only when it's in this mode:  http://prntscr.com/5y5mq5

I feel like increasing the avatar size for when it's on mobile browsers or when it's in the mode you've shown will make reading more cumbersome.

**Comment by iamisom** [comment]
If we can't separate the avatar sizes, then the size you've shown me is fine, as long as we increase the padding around it.

**Comment by olshiftyeye** [comment]
Done, just awaiting deployment to production.
