### ISSUE TITLE
More distinction between new and old notifications

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#149]
http://prntscr.com/5xyczz

While the image above shows old notifications, both new and old notifications look the same. It's difficult for me to determine which notifications I've already looked at.

**Comment by iamisom** [comment]
BTW:  I'm about to make a ton of github posts. Don't hate me.

**Comment by iamjohnp** [comment]
![](http://ss.imjp.me/20150128102912.png)

we'll plan on updating the background color of the "more notifications" page to match the background of the notifications dropdown. we'll then make sure that there is a different color state on the "more notifications" page for unread notifications that matches the same state in the notifications dropdown.

**Comment by iamisom** [comment]
Sounds good. Will we also have a Mark As Read button on the More Notifications page?

**Comment by iamjohnp** [comment]
yes, the same "x" will be present to the right of the time stamp.

**Comment by iamjohnp** [comment]
![](http://ss.imjp.me/20150128123200.png)

@mbizzle can you please do as instructed in the image above ^^? let me know if anything is unclear.

**Comment by olshiftyeye** [comment]
ready for deployment.

**Comment by iamisom** [comment]
Was this pushed live?

**Comment by olshiftyeye** [comment]
yup

![](http://ss.imjp.me/20150202192727.png)

again, probably cache issue.
