### ISSUE TITLE
More distinction between read and unread private messages

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#150]
http://prntscr.com/5xyi91

The top two messages in this image are unread; the bottom three messages are read. There's no distinction between the two. Can we create more distinction between the two, please?

**Comment by iamjohnp** [comment]
@iamisom i have a simple solution for this. let me mock it up for you.

**Comment by olshiftyeye** [comment]
@iamisom 
![](http://ss.imjp.me/20150129111745.png)

@mbizzle let's use the mail-4 icon from our solid icon pack, placed as shown above, for unread messages.

**Comment by olshiftyeye** [comment]
@iamisom this is going to take some significant work on our end, so i'm putting it into our someday pile for now.

**Comment by adamlieb** [comment]
I'm going to close out these issues that are "feature requests." We have a pretty good process with our SOWs for getting new features added in. I'd like to add feature requests there and leave this GitHub repo for actual bugs.
