### ISSUE TITLE
More distinction for pinned posts

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#151]
Steam forums:  http://prntscr.com/5xyizk
Our forums:  http://prntscr.com/5xyj5q 

Is it possible to make pinned posts a different color from unpinned threads? Something like this:  http://prntscr.com/5xyjuu (Ignore the underlining on the first thread. I'm just referring to the color.)

It's kind of difficult to see the difference between pinned and unpinned threads on our forums. I'm open to other suggestions here.

**Comment by iamjohnp** [comment]
@iamisom i'd recommend we update the color of the pin icon itself to help it stand out without making it a distraction. i threw together a few examples of colors below. do any of these seem ideal to you?

![](http://ss.imjp.me/20150128173741.png)

**Comment by iamisom** [comment]
Great idea. Let's go with the green tacks. That fits in with the Popularity gems.

**Comment by olshiftyeye** [comment]
@mbizzle can you update all of the pin icons in forums to #1fa941 please?

**Comment by olshiftyeye** [comment]
looks good! just awaiting completion of some other issues before we deploy.

**Comment by iamisom** [comment]
Was this pushed live?

**Comment by olshiftyeye** [comment]
yes

![](http://ss.imjp.me/20150202192627.png)

probably a caching issue if you're not seeing it.
