### ISSUE TITLE
Most notification emails aren't working for me

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#152]
Here are my notifications:  http://prntscr.com/5xylmq

I receive emails when someone sends me a personal message, but I haven't received an email when someone tagged me in a forum post, tags me in a thread, quotes my forum post or tags me in a blog comment. I haven't personally experienced any of the other notification settings, so I can't confirm if those aren't working properly either. Can we look into this, please?

**Comment by iamjohnp** [comment]
@iamisom i have confirmed this an issue and we're fixing it now.

**Comment by iamjohnp** [comment]
@iamisom when was the last time you received an email from activity on production (not staging)?

**Comment by iamisom** [comment]
On January 22, I received an email about a new private message.
On January 14, I received an email about a new private message.

Those are the only two emails that are in my trash bin going back to the beginning of the month.

For the record, I receive at least 3 private messages a day.

**Comment by iamjohnp** [comment]
that's helpful. thanks!

**Comment by olshiftyeye** [comment]
@iamisom we've made an update so i tested this on production and i received all of the proper emails. i'm going to close this out, but let me know / reopen this issue if you continue having problems.
