### ISSUE TITLE
Bug when hovering over a player's title

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#153]
https://www.dungeondefenders.com/2/topic/115001/bug-hover-over-title 
 
Hovering over a title in the forums (like Administrator) shows you the code behind the title, not the caption for it.
{"name":"Administrator","badge":"TElogo.png"} instead of Administrator.

**Comment by olshiftyeye** [comment]
looks complete on staging. i'll double check once we've deployed to production.

**Comment by iamisom** [comment]
Was this pushed live?

**Comment by olshiftyeye** [comment]
yes

![](http://ss.imjp.me/20150202192356.png)

probably a caching issue if you're not seeing it.
