### ISSUE TITLE
Bug:  DD1 Guides do not appear in the Guides search section

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#156]
Repro:

Step 1:  Click on DD1 guides. Find a guide to use as an example. For this one, we'll use this:  https://www.dungeondefenders.com/1/guides/46675/new-layout-planner-ddplannerczokalapikcom

Step 2:  Copy the thread title and enter it into the search.

Step 3:  Notice that the guide does not appear in the Guides section. It does, however, appear in the Forum Topics section.

**Comment by AnthonyKinson** [comment]
Hey,

Guides have now been properly re-assigned for DD1 and are listing properly in live search.

![](http://ss.anthonykinson.co.uk/280115173527.png)
