### ISSUE TITLE
Notification Changes

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#157]
Note:  For all changes below, make the names of threads/blogs a different color than the rest of the text to highlight that it's a name.

**1)  For any notifications dealing with thread tracking, replace "a thread you track" with the name of the thread to the notification.**

Example:

Current:  R-Kane and 4 others replied to a thread you track.
New:  R-Kane and 4 others replied to Letting Sub-Cores Get Destroyed?

**2)  For any notifications dealing with comment liking/quoting, add the text of your comment to the notification up to a defined character count.**

Example:

Current:  AussieMark liked your forum post.
New:  AussieMark liked your forum post:  "The panel went very well! I thought I..."
Current:  AussieMark quoted your forum post.
New:  AussieMark quoted your forum post.  "The panel went very well! I thought I..."

**3)  For any notifications dealing with username tagging, change the text "tagged" to "mentioned" and add the thread or blog name to the notification.**

Example:

Current:  R-Kane tagged you in a forum post.
New:  R-Kane mentioned you in This game is the absolute worst.

**4)  For any notifications dealing with replies to blog comments, add the name of the blog.**

Current:  Gutu replied to your blog comment.
New:  Gutu replied to your blog comment on Trendy at PAX South 2015.

**Comment by adamlieb** [comment]
I'm going to close out these issues that are "feature requests." We have a pretty good process with our SOWs for getting new features added in. I'd like to add feature requests there and leave this GitHub repo for actual bugs.
