### ISSUE TITLE
More distinction for links on the DD2 site

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#158]
Current:  http://prntscr.com/5xzk55
Suggested:  http://prntscr.com/5xzkbl 

Can we automatically bold hyperlinks on the DD2 site so that they stand out a bit more?

**Comment by iamjohnp** [comment]
@iamisom to me the bolding doesn't really add to it at all. however, i think underlining it should help. do you agree?

**Comment by iamisom** [comment]
The issue is the blue color for hyperlinks makes it appear less bold/less defined than the normal white text. Underlining it will help. What if we did both? Would that be too much?

**Comment by iamjohnp** [comment]
@iamisom sure!

@mbizzle when you get a moment, can you make sure that hyperlinks on the DD2 site get both bolded and underlined? reassign to me when complete.

**Comment by olshiftyeye** [comment]
@mbizzle here is an OP and a reply...
![](http://ss.imjp.me/20150129092555.png)

- [ ] it looks like you applied bolding to replies, but they should be underlined as well
- [ ] OP links have neither bolding nor underline

**Comment by olshiftyeye** [comment]
ready for deployment.

**Comment by iamisom** [comment]
Was this pushed live?

**Comment by olshiftyeye** [comment]
yes

![](http://ss.imjp.me/20150202192500.png)

probably a caching issue if you're not seeing it.

**Comment by iamisom** [comment]
https://www.dungeondefenders.com/2/topic/116998/

Newly created link.

**Comment by olshiftyeye** [comment]
this is what i see:

![](http://ss.imjp.me/20150202192924.png)
