### ISSUE TITLE
Forum post background/thread title background color change on DD2 site

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#159]
Current Forum Post Background:  http://prntscr.com/5xzkz6
Suggested Forum Post Background: http://prntscr.com/5xzlhn
Current Thread Title Background:  http://prntscr.com/5xzlns 
Suggested Thread Title Background:  http://prntscr.com/5xzll9 

Can we change the background of regular user forum posts and thread title bars to #26272c? Regular user means that they are not a Defense Councilor, Administrator, Development Team Member or a Moderator.

**Comment by iamjohnp** [comment]
yes, i think this looks a bit tighter actually. @mbizzle take it away!!

**Comment by olshiftyeye** [comment]
@mbizzle it looks like the darker "forum post background" isn't being applied to the nomnom user group:

![](http://ss.imjp.me/20150129094741.png)

**Comment by olshiftyeye** [comment]
ready for deployment.
