### ISSUE TITLE
Add title of thread to Tab Information

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#160]
http://i.imgur.com/HIhrK42.png 

Can we add the name of the thread topic to tabs? For example, the tab in the above linked image should read "Legendary Loot. - Dungeon Defenders 2 Forum" and not what it currently says.

For users who open multiple threads at once, this is particularly useful.

**Comment by rsyvarth** [comment]
This should be done and on staging now.

**Comment by rsyvarth** [comment]
Leaving open until on production

**Comment by olshiftyeye** [comment]
@iamisom this is done now and on production.
