### ISSUE TITLE
Bug:  Notification dropdown disappears when click "Mark As Read"

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#161]
Whenever you click "Mark As Read" on a notification in the dropdown, the dropdown menu disappears, and the user has to reopen the dropdown menu again. Can we keep this dropdown menu open when you mark a notification as read?

**Comment by iamjohnp** [comment]
@iamisom we can do that. i'll get @mbizzle on it right away.

**Comment by olshiftyeye** [comment]
ready for deployment.
