### ISSUE TITLE
Moderation Backend Page

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#162]
We need a backend page for player moderation. This page should be viewable by moderators and administrators. This page needs:

**1)  A widget for currently active reports. This widget should have three columns:  the first main column will be a notification-style feed detailing the reports; the second column will contain the reason the material was reported; the third column will contain a button for each report that lets mods/admins "Mark As Handled." Reports that are marked as Handled will be removed from this widget and put into the widget detailed in Number 2.**

Each report should contain the following information
A)  Type:  Thread, Forum Post, Guide, Guide Comment, Blog Comment, Caption, Screenshot, Fan Art
B)  Name of the Reporter with link to the Reporter's Profile 
C)  Name of the Reported with link to the Reported's Profile
D)  Link to the offending material (the entire notification text string should act as a hyperlink)
E)  Time/date of report

Examples:
R-Kane has reported iamisom's forum post:  "If I ever see you around these parts..." (3:48 PM, Jan 27, 2015)
R-Kane has reported iamisom's thread:  "I HATE EVERYONE" (3:45 PM, Jan 27, 2015)
R-Kane has reported iamisom's guide:  "HOW TO HATE EVERYONE"  (3:42 PM, Jan 27, 2015)
R-Kane has reported iamisom's guide comment:  "Well that's because..." (3:40 PM, Jan 27, 2015)
R-Kane has reported iamisom's blog comment:  "kfjskfjslfjskldfs..." (3:35 PM, Jan 27, 2015)
R-Kane has reported iamisom's caption. (3:32 PM, Jan 27, 2015)  
R-Kane has reported iamisom's screenshot. (3:30 PM, Jan 27, 2015)
R-Kane has reported iamisom's fan art. (3:25 PM, Jan 27, 2015)

The "Reason for Report" column should have a character limit of 150 characters.

**2)  A widget for handled reports. This is so we have a history of our reports. This widget should contain two columns:  a column containing the name of the mod/admin who handled the report and a column containing the report details as outlined in Number 1.**

Examples:

Handled By  |  Report Details

iamisom       |  R-Kane has reported iamisom's forum post:  "If I ever see you around these parts..." (3:48 PM, Jan 27, 2015)
alhanalem   |  R-Kane has reported iamisom's thread:  "I HATE EVERYONE" (3:45 PM, Jan 27, 2015)

**3)  A list of users who are currently suspended.**

**4)  A list of users who are currently marked as trolls.**

**5)  A list of users who are permanently banned.**

**Comment by adamlieb** [comment]
I'm going to close out these issues that are "feature requests." We have a pretty good process with our SOWs for getting new features added in. I'd like to add feature requests there and leave this GitHub repo for actual bugs.
