### ISSUE TITLE
Report a Post Function

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#163]
Please add a report function in the ellipsis dropdown menu on posts/threads. By selecting this option, a popup should appear that lets users fill in a text field (character limit:  150 characters). After selecting Submit, a report will be sent to the Moderation Backend Page as described in this Github task:  https://github.com/DuxterInc/trendy-community/issues/162

**Comment by olshiftyeye** [comment]
this is a pretty hefty implementation, but something we're working on. just a heads up this will be implemented at some point in the not-too-distant future. but it will take some time before it's ready to deploy.

**Comment by iamisom** [comment]
Sounds good.

**Comment by iamisom** [comment]
Any ETA?

**Comment by olshiftyeye** [comment]
No ETA quite yet. As with #167 and #168 this is in queue, but it's a fairly complex system. I'll definitely update you when it's ready :)

**Comment by adamlieb** [comment]
I'm going to close out these issues that are "feature requests." We have a pretty good process with our SOWs for getting new features added in. I'd like to add feature requests there and leave this GitHub repo for actual bugs.
