### ISSUE TITLE
What's New Page Filter

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#164]
Add a new section in the Settings menu called "What's New Page Settings." Similar to the Notifications menu, this page will let players filter threads from the What's New page so that they only see content from subforums that interest them. If a subforum gets filtered, any threads created or marked unread will not be shown in the What's New page.

These filters are:

**Dungeon Defenders II**
* General Discussion
* Suggestions
* Patch Notes
* Tech Support & Bug Reports

**Dungeon Defenders Eternity**
* General Discussion
* Trading
* Technical Support
* Suggestions

**Dungeon Defenders**
* General Discussion
* Trading
* Technical Support

**Other**
* Defender's Lounge
* Website Feedback

**Comment by adamlieb** [comment]
I'm going to close out these issues that are "feature requests." We have a pretty good process with our SOWs for getting new features added in. I'd like to add feature requests there and leave this GitHub repo for actual bugs.
