### ISSUE TITLE
"What's New?" Page

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#165]
This is a feature from our old vBulletin site that is highly requested by our community. In essence, this is a new subforum that includes threads from every subforum that are currently unread. When a thread becomes read, it is removed from this list. When a thread gets a new reply or a new thread is created, it is added to this list. The What's New Page will include threads from all subforums from all sites unless otherwise filtered out. (More info on the What's New filter here:  https://github.com/DuxterInc/trendy-community/issues/164) 

**Why is this important?** Because players like "completing" the forums by reading everything, so they like having a page where they can track everything that needs to be read in order to complete the forums. It's also easier to keep on top of new activity this way than the Activity Feed.

This page will be accessible by a button added next to the Forum Rules button on the forum homepage. This button will be called "What's New?"

**Comment by adamlieb** [comment]
I'm going to close out these issues that are "feature requests." We have a pretty good process with our SOWs for getting new features added in. I'd like to add feature requests there and leave this GitHub repo for actual bugs.
