### ISSUE TITLE
Option to increase posts/threads per page

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#166]
Add an option to the settings page that lets players increase posts per page and threads per page. Use the following filters as options:

* 10
* 20
* 50
* 100

**Comment by iamjohnp** [comment]
@iamisom if you have a sort of middle ground number that you think would be ideal to reset as the default number of replies/threads per page (they don't have to be the same for replies and threads), then we're happy to update that. i will note that 100 will be too many and cause performance issues. having another option for users to deal with that just clutters up the UI is not something we'd prefer to do.

**Comment by iamisom** [comment]
The issue here is player customization and feature parity with vBulletin. This is an option that was in our previous forums that we have lost and will continue to be a sore spot for our community when they compare the two. Is it not possible to include a dropdown menu in the Settings for this? That should be a fairly uncluttered way of doing this. As for the 100 posts, that's fine to exclude.

**Comment by iamjohnp** [comment]
one thing we're not trying to do **at all** is have feature parity with VB. we're actually trying to simplify and make a better experience all around. in that vein, showing a set number of replies/threads for every user provides consistency and clarity. it also keeps the site as performant as it can be. 

again, i think we want to find the "ideal" number of posts to show at once, and then make that the default. if you think 10 isn't ideal, what about 15? 20? would you like to ask a group of users and see what they would set it to if they could set it to anything?

**Comment by iamisom** [comment]
In what ways does keeping posts/threads consistent across all users improve the user experience? Wouldn't providing choice improve the user experience? I'd love to hear your thoughts on the matter.

**Comment by olshiftyeye** [comment]
i talked with the devs about this and it isn't really something we can implement. there are too many dependencies with performance issues, URL structures and object model relations. we **can**, however, universally change the number of posts that display from 10 to some other number. i'd recommend staying at 25 or fewer so as not to affect page loads. 

how many threads do you think we should load at a time?

**Comment by iamisom** [comment]
We should stick to the default at the moment. If the community clamors more for this in the future, I'll reopen the conversation.
