### ISSUE TITLE
Button to Jump to First Unread Post

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#167]
Thread List:  http://prntscr.com/5xzz3t
Thread Details Box:  http://prntscr.com/5xzz7d

Add a button to the Thread List and Thread Details Box to let users go directly to the first unread post in a thread. This is great for threads that have received a ton of activity while the user was away and lets the user get right back where he/she left off.

**Comment by olshiftyeye** [comment]
![](http://ss.imjp.me/20150130103330.png)

@mbizzle the design is above. please use mail 4 icon from our solid icon pack. in the case that there is no dev post, the envelope should appear in that position. also, the envelope should only appear to an individual user if that user has not read 1 or more messages in that thread. clicking the icon should nav the user to the oldest unread message in the thread.

**Comment by olshiftyeye** [comment]
@iamisom this is also going to take some significant work on our end, so i'm putting it into our someday pile for now.

**Comment by iamisom** [comment]
This is a highly requested feature from our community. Is there any chance that we can bump this up?

**Comment by iamisom** [comment]
Bumping again. This is highly requested.

**Comment by olshiftyeye** [comment]
Same as #168 this is in queue. Will report back when complete.

**Comment by adamlieb** [comment]
I'm going to close out these issues that are "feature requests." We have a pretty good process with our SOWs for getting new features added in. I'd like to add feature requests there and leave this GitHub repo for actual bugs.
