### ISSUE TITLE
Clicking the white TE logo on a thread will take you to the first Dev Post in the thread

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#168]
http://prntscr.com/5y006s

When a user clicks the white TE logo, they should be taken to the first Dev Post in the thread.

**Comment by olshiftyeye** [comment]
@mbizzle i think this is pretty self-explanatory. let me know if you have questions.

**Comment by mbizzle** [comment]
@rsyvarth can you add the same topicPosition parameter to the forum listing as you did for dev tracker and the notifs for the redirect? 

https://dd-aws.duxsites.com/2/forum/15/defense-council-general-discussion

**Comment by iamisom** [comment]
Any ETA on this?

**Comment by olshiftyeye** [comment]
This is something we'll be implementing sometime in the coming weeks. We've currently got it in queue to build out the functionality (not exactly trivial). Will update you when it's ready for deployment. Let me know if you have any questions.

**Comment by adamlieb** [comment]
I'm going to close out these issues that are "feature requests." We have a pretty good process with our SOWs for getting new features added in. I'd like to add feature requests there and leave this GitHub repo for actual bugs.
