### ISSUE TITLE
Request:  Change the "Thread Started On" details

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#171]
https://www.dungeondefenders.com/2/topic/116843/thread-started-vs-last-post

The thread above has more details. I'd like it if we kept the username color the same, but other than that, I agree with this thread.

**Comment by olshiftyeye** [comment]
@mbizzle can you please make this...

![](http://ss.imjp.me/20150203101941.png)

...look like this?

![](http://ss.imjp.me/20150203101918.png)

To be clear, I'm referring to the [create date](http://ss.imjp.me/20150203102122.png) for a thread on a [thread list](https://www.dungeondefenders.com/2/forum/20/website-feedback).

**Comment by mbizzle** [comment]
@olshiftyeye want to do a quick staging check?

**Comment by olshiftyeye** [comment]
acceptable!
