### ISSUE TITLE
Request:  Global notification for when an admin posts a new blog or a new Initiative poll

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#172]
I talked with the Council today, and they said they would like to get notified whenever we make a new blog or a new Initiative. Are we able to do this?

Also, it would be great if it could follow this format:

"[Username] posted a new [development blog/Initiative]: [title of blog/title of Initiative]"

**Comment by adamlieb** [comment]
I'm going to close out these issues that are "feature requests." We have a pretty good process with our SOWs for getting new features added in. I'd like to add feature requests there and leave this GitHub repo for actual bugs.
