### ISSUE TITLE
Request/Urgent:  Add "Feedback" subforum to DD2

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#173]
Can you please add a Feedback subforum to the DD2 forums as soon as possible? We have a patch going live later this week, and I'd like this subforum to be up at that time.

Only admins/moderators/development team members may create new threads in this subforum, but anyone can make a reply to a thread. This subforum is viewable by everyone.

New hierarchy should be:
Defense Council General Discussion
Defense Council Suggestions
General Discussion
Feedback
Suggestions
Patch Notes
Tech Support & Bug Reports
Defender's Lounge
Website Feedback
Trendy Only
Archive

**Comment by olshiftyeye** [comment]
which character would you like in the background?
![](http://ss.imjp.me/20150202163307.png)

**Comment by iamisom** [comment]
Do we have an Apprentice background?

**Comment by olshiftyeye** [comment]
let me check, also should we call it "game feedback" or something more specific? we have website feedback and suggestions, so it might help to add an identifier to the forum name.

**Comment by olshiftyeye** [comment]
![dd2_buttonbackgrounds](https://cloud.githubusercontent.com/assets/4674805/6011562/8306f586-aafa-11e4-8807-a6d069d62098.png)

**Comment by iamisom** [comment]
Good call on "Game Feedback." Let's go with that. :)

We should use the Apprentice background. We should also think for a moment about the background images of the other subforums (excluding Defense Council GD, Defense Council Suggestions, Trendy Only and Archive). 

![krhx1j7](https://cloud.githubusercontent.com/assets/9043673/6011610/e56a3e02-ab0b-11e4-8d5d-c1626da08834.png)

We should make sure that we aren't repeating an image back to back. Agree? Disagree?

**Comment by olshiftyeye** [comment]
How's this for images (updated so there won't be any of the same images above/below or left/right of each other)?

Defense Council General Discussion
![](https://cloud.githubusercontent.com/assets/4674805/4450531/b933d8c2-4826-11e4-9525-92b84d5c750c.png)

Defense Council Suggestions
![](https://cloud.githubusercontent.com/assets/4674805/4450537/ccf61d7a-4826-11e4-8ead-5966c24d7db0.png)

General Discussion
![](https://cloud.githubusercontent.com/assets/4674805/4450541/d2a825d8-4826-11e4-9520-c2d6b02961eb.png)

Game Feedback
![](https://cloud.githubusercontent.com/assets/4674805/4450534/c6742f0a-4826-11e4-9e0a-810ae2782634.png)

Suggestions
![](https://cloud.githubusercontent.com/assets/4674805/4450532/c0717964-4826-11e4-821c-6941914bf142.png)

Patch Notes
![](https://cloud.githubusercontent.com/assets/4674805/4450528/b2f55148-4826-11e4-9cf6-097b1ef51cdf.png)

Tech Support & Bug Reports
![](https://cloud.githubusercontent.com/assets/4674805/4450525/ac9e8e04-4826-11e4-9480-c0b2d6bd7319.png)

Defender's Lounge
![](https://cloud.githubusercontent.com/assets/4674805/4450531/b933d8c2-4826-11e4-9525-92b84d5c750c.png)

Website Feedback
![](https://cloud.githubusercontent.com/assets/4674805/4450537/ccf61d7a-4826-11e4-8ead-5966c24d7db0.png)

Trendy Only
![](https://cloud.githubusercontent.com/assets/4674805/4450532/c0717964-4826-11e4-821c-6941914bf142.png)

Archive
![](https://cloud.githubusercontent.com/assets/4674805/4450534/c6742f0a-4826-11e4-9e0a-810ae2782634.png)

**Comment by iamisom** [comment]
Perfect. Thanks!

**Comment by olshiftyeye** [comment]
@AnthonyKinson can you make it so? please reassign to @mbizzle for any front-end magic that needs to happen here.

**Comment by AnthonyKinson** [comment]
Sure, will have this up just as soon as I find my wand.

**Comment by AnthonyKinson** [comment]
ok this is done @mbizzle.

You need to special case the frontend. ONLY show "start thread" buttons to groups with id **3**, **4**, **6** ($user->users_group->id) When the Forums category ID = **26**

This has been done before for "Patch Notes" (category id 24) so you shoudl be able to duplicate the code there. API will refuse to allow thread creation by anyone who is not Admin, Mod or Dev, but we want to hide the button to everyone else.

Once this is done, and before it is deployed live, please give me a shout.

**Comment by AnthonyKinson** [comment]
@mbizzle don't worry about this, i'm having thomas do it as he done it before, shoudl make this real quick and save you jumping off what you're currently doing.

**Comment by AnthonyKinson** [comment]
@olshiftyeye this is all live except for the background image. Please reassign this issue to whoever should add this in.

**Comment by mbizzle** [comment]
bgs updated

**Comment by olshiftyeye** [comment]
@mbizzle can you fix the order of the categories? they aren't currently ordered correctly.

**Comment by olshiftyeye** [comment]
acceptable!!
