### ISSUE TITLE
Avatar update issues

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#174]
1)  Avatars on the forums are oddly shaped. 
http://prntscr.com/60f1ra

2)  Avatars were enlarged on the blogs, blog comments, guides, guide comments and initiative comments, which we did not want. We only wanted the avatar size increased on the forums.
http://prntscr.com/60f1fv
http://prntscr.com/60f1oi

**Comment by olshiftyeye** [comment]
avatars are looking fine for me on forums:
![](http://ss.imjp.me/20150202193114.png)

but you're right, somehow the update got pushed to other areas of the site. fix coming.

**Comment by iamisom** [comment]
I just had to delete my browser cache. Thanks for the update on the fix.

**Comment by olshiftyeye** [comment]
@iamisom this is now on production. closing ;)
