### ISSUE TITLE
Request:  Like/Quote Button Hover Change for DD2

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#176]
I love the way the like and quote buttons on the DDE site feel when you hover over them. The text on the buttons move down slightly when you hover over them. Can we replicate that for the DD2 site?

**Comment by olshiftyeye** [comment]
@mbizzle i think for dd2 we should flip the gradient on the background of these buttons when they are hovered over.

![](http://ss.imjp.me/20150205135232.png)

PM me on slack when you dive into this and we can chat further.

**Comment by olshiftyeye** [comment]
ready for deployment.

**Comment by iamisom** [comment]
When is this going to be deployed?

**Comment by olshiftyeye** [comment]
Apologies @iamisom I thought we had deployed this already. Will get it pushed ASAP.

**Comment by olshiftyeye** [comment]
@iamisom this was just deployed.
