### ISSUE TITLE
Request:  Hover Change for Subforums

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#177]
http://us.battle.net/d3/en/forum/

I love the way the subforums feel on the Diablo III forums. They feel like elements that you can click. Is there someway that we can add a hover change for our subforums so they feel like more interactive/button elements?

**Comment by olshiftyeye** [comment]
@mbizzle for dd2, let's highlight the icon and category title in #ffeca6 on hover.
![](http://ss.imjp.me/20150205131358.png)

for dd1/dde, let's highlight the icon and category title in #e8ab64 on hover.
![](http://ss.imjp.me/20150205131309.png)

**Comment by iamisom** [comment]
What's the status report on this?

**Comment by olshiftyeye** [comment]
Not yet implemented (even on staging). Will chat with the team and get back to you.

**Comment by adamlieb** [comment]
I'm going to close out these issues that are "feature requests." We have a pretty good process with our SOWs for getting new features added in. I'd like to add feature requests there and leave this GitHub repo for actual bugs.
