### ISSUE TITLE
Notif counters inconsistent

### ISSUE THREAD

**Issue by kaiheilos** [DuxterInc/trendy-community#178]
![screenshot 2015-02-18 19 40 58](https://cloud.githubusercontent.com/assets/9444563/6255243/8744ed02-b7a6-11e4-8215-7143de05d50a.png)
DD2 doesn't have a number when there's no new notifs but DDE/1 do

**Comment by olshiftyeye** [comment]
Reopened #155 as that's where this was originally handled.
