### ISSUE TITLE
Icon size inconsistency

### ISSUE THREAD

**Issue by olshiftyeye** [DuxterInc/trendy-community#180]
From David:

> Isom gave me a custom title and my icon became huge. Also other mods have a tiny icon by comparison to Defence Council members
![screenshot 2015-02-17 20 35 59](https://cloud.githubusercontent.com/assets/9444563/6236740/06891f38-b6e5-11e4-89e4-f8ba738a549e.png)

> Tested on a couple other people and can confirm it's a custom title issue. Setting one makes the image full size (80x80)

**Comment by rsyvarth** [comment]
This issue has been inactive for awhile and it doesn't seem like there is any further action necessary so I am going to go ahead and close the issue. If you still believe that there are changes that need to be made for this issue then please reopen it and reply with any specifics that you feel still need to be addressed.
