### ISSUE TITLE
Extra Analytics Data

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#181]
1.  Below "Total New Users," we need a new metric:  "Total New Users Who Became Active." This metric should show the number of Total New Users for that month who made at least one post during the month. This will help us calculate how many New Users became Participants of the community.

2.  We need to evaluate the conversion ratio of Participants to Regular Members in order to figure out where people are dropping out of the community. Underneath "Total Admin Posts," we need several new charts:

    A) New User Contributions Since Joining:  Using the Total New Users Who Became Active metric of the month selected, calculate how many posts those members have made in their lifetime and put them into buckets. This will be a six-column chart with the following buckets:
     1 to 5 Posts
     6 to 10 Posts
     11 to 15 Posts
     16 to 20 Posts
     21 to 25 Posts
     26+ Posts

    B) New Users Still Active Months Since Joining:  Using the Total New Users Who Became Active metric of the month selected, calculate how many of those members have made a post over the next six months. NOTE:  This doesn't mean that users have to had made a post in every consecutive month. This graph takes the last post date month of the user and places it into the chart. This is a long-term graph, so we do expect data to not be available until that time has passed. This will be a six-column chart.
     1
     2
     3
     4
     5
     6

    C)  New Users Weeks Before Leaving:  Using the Total New Users Who Became Active metric of the month selected, calculate how soon those members left the community. "Left" means that no active post was made during this time. This will be a four-column chart. The parenthetical information does not need to be displayed on the chart -- it's for clarification purposes.
    Less Than 1 (0-6 days)
    1 (7-13 days)
    2 (14-20 days)
    3 (21-31 days)

**Comment by iamisom** [comment]
This is fairly urgent. I am okay with getting the first part in before getting the others, but I need to figure out where some of our community issues are residing.

**Comment by olshiftyeye** [comment]
@iamisom we can get #1 pushed tomorrow, since it's super low burden. the others are a bit more intense so we'll not be able to get those live for a bit.

**Comment by olshiftyeye** [comment]
@rsyvarth just reassign to me when that's done, if you would.

**Comment by rsyvarth** [comment]
Part 1 has been added on production. The information is under "New Monthly Active Posters" which is just the intersection of the set of members in the "Monthly Active Posters" chart with the set of members who have joined in the selected month.

**Comment by olshiftyeye** [comment]
thanks rob! @iamisom #1 is now deployed to production. let me know if there are any immediate changes needed to that particular report. otherwise, we'll get to the other, heavier reports soon.

**Comment by iamisom** [comment]
Thanks! This is perfect. I appreciate the breakdown by game, too!

**Comment by olshiftyeye** [comment]
:+1:

**Comment by iamisom** [comment]
The stats for March aren't loading in. Is this a bug?

**Comment by olshiftyeye** [comment]
Might be a bug. Looking into it.

**Comment by rsyvarth** [comment]
Resolved and pushed to production
