### ISSUE TITLE
Dev Tracker Cache Issue

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#183]
https://www.dungeondefenders.com/2/forums/devtracker

When you click Load More Posts, it loads a few more posts, but then it loads in the previously loaded posts again.

**Comment by olshiftyeye** [comment]
hmm, @iamisom none of us are able to reproduce this issue. can you provide some more details about how you're running into this issue and about how often?

**Comment by rsyvarth** [comment]
This issue has been inactive for awhile and it doesn't seem like there is any further action necessary so I am going to go ahead and close the issue. If you still believe that there are changes that need to be made for this issue then please reopen it and reply with any specifics that you feel still need to be addressed.
