### ISSUE TITLE
Error when trying to view messages via notification bar/dropdown

### ISSUE THREAD

**Issue by f1297309** [DuxterInc/trendy-community#184]
So when I click this message: 

![notification](https://cloud.githubusercontent.com/assets/11444684/6623166/a6be6b32-c8b7-11e4-98c8-b1ee41025430.png)

I get logged out no matter where I am and get:

![view_message](https://cloud.githubusercontent.com/assets/11444684/6623139/7dddf944-c8b7-11e4-8a1a-f53e43952a76.png)

But I can view the message fine via just going to Messages first then clicking the conversation.

**Comment by adamlieb** [comment]
I believe this issue is fixed or cannot be replicated. If you still have this happen please re-open and post any details that will help us reproduce and fix.
