### ISSUE TITLE
Fanart previews in the media section

### ISSUE THREAD

**Issue by kaiheilos** [DuxterInc/trendy-community#185]
If a person uploads a piece of media that's not the same resolution as the preview box, it gets smooshed in the preview

Example;
https://www.dungeondefenders.com/2/media/fanart/21264
https://www.dungeondefenders.com/2/media

**Comment by olshiftyeye** [comment]
@mbizzle can we set the container for the preview image and then keep the aspect ratio intact for the uploaded image (similar to what we're doing elsewhere on our single column newsfeeds)?
