### ISSUE TITLE
Forum Loading Issue When Logged Out

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#186]
http://prntscr.com/6iuumv

This is fixed on a refresh, but new users might not realize that the forums aren't supposed to look like this.

**Comment by olshiftyeye** [comment]
@iamisom I'm unable to reproduce this. I think this might be a cache issue that a new user wouldn't experience. In fact, only users that had visited the site before we implemented the forum tile backgrounds would even possibly see this. 

Is this happening to you often? Or just happened once?

**Comment by iamisom** [comment]
This happens every time I have been logged out and click the forums.

**Comment by olshiftyeye** [comment]
Ok, this definitely won't happen for new users. Can you clear your cache and see if that fixes?

**Comment by adamlieb** [comment]
So confirmed this is only an issue for admins who have privileges above what others have. When you log out sometimes the things you could see as an admin are cached, then you try to access them and you have no access. This will fix when you login or clear your cache. No "users" will get this experience.
