### ISSUE TITLE
Usernames with Special Characters

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#187]
https://www.dungeondefenders.com/2/topic/118144/set-a-du-limit-for-each-player-in-the-comunity-lobby-and-autosell-defenses-when-a-player-leave-the-lobby

We're getting some crazy usernames. Is there anyway to stop this?

**Comment by adamlieb** [comment]
Those names come from steam account imports. Username rules were derived from steam's so that gamers can use the same name across game and community. 



—AL

**Comment by rsyvarth** [comment]
This issue has been inactive for awhile and it doesn't seem like there is any further action necessary so I am going to go ahead and close the issue. If you still believe that there are changes that need to be made for this issue then please reopen it and reply with any specifics that you feel still need to be addressed.
