### ISSUE TITLE
Posting a link requires the user to double-click inside the link popup textbox

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#191]
When you click the Link button in the text editor, the Link popup appears. If you click once in the linking text field, it does not actually select the text field. You must click the text field twice to be able to write text inside of it.

**Comment by rsyvarth** [comment]
I cannot reproduce this issue on production. It is possible that it was resolved as part of the milestone 1 rollout. Please re open this issue if you can reproduce.
