### ISSUE TITLE
Urgent:  Forum avatars aren't loading

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#195]
Several other members have confirmed.

https://www.dungeondefenders.com/2/topic/118725/trolls-unkickable-and-game-ruining

**Comment by olshiftyeye** [comment]
We've identified the cause and we're fixing it now.

**Comment by adamlieb** [comment]
Issue came up with the image resizer, all images are still there, they are just not being properly resized some places like the forums. Will be back in 1-2 hours.

**Comment by adamlieb** [comment]
Fixed.
