### ISSUE TITLE
Bug:  Issues Remaining Logged In

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#196]
For the past few months, we've received various complaints about not being able to stay logged in. Someone mentioned that you have to remove steamcommunity cookies to remain logged in if this issue occurs. This might have something to do with the oauth stuff getting hung up on something.

**Comment by iamisom** [comment]
"When you log in, you get an access token, that is supposedly valid for 604800 seconds, or 7 weeks. You also get a refresh token. The purpose of the refresh token is to fetch a new access token upon expiry or invalidation of the access token. However, it appears that the functionality for fetching a new access token, using said refresh token, is missing or extremely unreliable."

**Comment by AnthonyKinson** [comment]
Hi,

Steam only provides a method of validating the user owns their steam account, which is then passed over to log in a user without using their local email and passwords. Session's are maintained locally (not via steam or steam cookies). 

You are correct about the refresh tokens, right now sessions will expire and the refresh token's are not being used to renew the session automatically which we are aware of. I'm working to get that functionality in on our next wave of updates.

**Comment by rsyvarth** [comment]
I believe any issues with this have been resolved with the milestone 1 rollout. Please make a new issue if you experience any more trouble.
