### ISSUE TITLE
DD1 new usergroup and sub forums

### ISSUE THREAD

**Issue by adamlieb** [DuxterInc/trendy-community#197]
TO BE DONE AT ~10 AM ON 5/6 BASED ON JOSH'S WORD. 

In the DD1 forum, I will need two subforums and one new usergroup, but these cannot go live until tomorrow when I give the word as they hinge upon an announcement:

1)  A new usergroup:  Community Development Team. No new public-facing title right now. For the time being, this should be a usergroup purely to give them access to a new subforum.

2)  A new subforum:  Community Development (Private). Only people in the Community Development Team, Moderator, Trendy, Nom Nom and Admin usergroups can see this forum. Anyone of these usergroups can make a new thread or new post here.

3)  A new subforum:  Community Development. Open subforum for everyone to comment/post threads on.

@AnthonyKinson

**Comment by rsyvarth** [comment]
This issue has been inactive for awhile and it doesn't seem like there is any further action necessary so I am going to go ahead and close the issue. If you still believe that there are changes that need to be made for this issue then please reopen it and reply with any specifics that you feel still need to be addressed.
