### ISSUE TITLE
Usergroup Bug:  CDT users have old grey background on the DD2 forums

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#198]
http://prntscr.com/72f51p

**Comment by adamlieb** [comment]
what is the expected behavior?

**Comment by iamisom** [comment]
It's expected that they'll have the new dark grey background color.

**Comment by adamlieb** [comment]
Can you link me to that wherever it is, the dark grey you want it to be? Is this a change? Was it dark grey and reverted back to light grey?

**Comment by iamisom** [comment]
https://www.dungeondefenders.com/2/topic/119813/pet-food-probability

It's because the Community Development Team usergroup doesn't have the new dark grey background color set for the DD2 forums.

**Comment by adamlieb** [comment]
This has been resolved.
