### ISSUE TITLE
Clicking "Load More Posts" on the Caption Contest app causes posts to appear twice

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#199]
It double loads new posts.

**Comment by adamlieb** [comment]
I can't seem to repro this. What are you doing and what is happening? I did notice that the last post before load more, and the first post after loading more were created by the same person...but they were different captions altogether. Perhaps I am looking for the wrong thing.

**Comment by iamisom** [comment]
1. Go to https://www.dungeondefenders.com/2/captions on Google Chrome.
2. Notice the first caption.
3. Scroll down. After 9 more captions (10 in total, counting the first caption you read), the 10 loaded captions repeat.
4.  Click Load Posts. 20 more captions load -- 10 new captions and 10 repeats of those new captions.

**Comment by adamlieb** [comment]
This is resolved.
