### ISSUE TITLE
People are having trouble getting the caption image to load on Google Chrome

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#201]
"To be certain, this is the exact error I'm getting on Chrome, where the image won't load: Image from origin 'https://duxsite-trendy.s3.amazonaws.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.dungeondefenders.com' is therefore not allowed access."

https://www.dungeondefenders.com/2/topic/119806/new-caption-contest?page=2

**Comment by rsyvarth** [comment]
This issue should have been resolved with a fix that went out about a month ago
