### ISSUE TITLE
YouTube/Forums conflict

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#206]
https://www.dungeondefenders.com/2/topic/121156/bug-youtubedd-forums-conflict

User was watching a YouTube playlist with the forums open in another tab. Every time the playlist moved to the next track, the DD Forums moved to another thread (most likely the next).

**Comment by adamlieb** [comment]
What he is describing sounds completely impossible. Can you reproduce this? He could be using a browser plugin/extension for changing tracks that is somehow navigating other websites. That could be possible. It is impossible for one browser tab to control what is going on in another browser tab without any extra plugin/extension. 

You can ask him for a more detailed description or video. I'd definitely bring up the browser plugin issue.

There is definitely no bug here.
