### ISSUE TITLE
Some notifications aren't appearing for users

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#207]
https://www.dungeondefenders.com/2/topic/121057/notifications-not-workingagain

"That post by Isom does not appear in my notifications (nor under "more notifications" which also does not include the three posts preceding Isom's in that thread, only the like) and you can see that it should be visible in that list of five, which goes back about 48 hours due to the influence points gained for signing in each day."

**Comment by Draco18s** [comment]
I'll just juke in here with what I found in my notifications this morning.

http://s17.postimg.org/60y1hoctr/notifications.png
http://s4.postimg.org/cu12e06gt/dropdown.png

I was able to find the posts via the user's profile.

http://s17.postimg.org/58vu1upkf/posts.png

**Comment by olshiftyeye** [comment]
quick tip, using `![](Image Link)` will actually preview the image in the post :)

**Comment by Draco18s** [comment]
#KnowledgeIsPower
I don't use GitHub much, but I'll try and remember that.

**Comment by adamlieb** [comment]
Don't think you're still seeing this. If so please respond back!

**Comment by Draco18s** [comment]
Its really hard to tell, and I haven't been as vigilant about reading forum threads lately.

**Comment by adamlieb** [comment]
No worries just let me know if you do.
