### ISSUE TITLE
Difficulty reading "like" numbers

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#208]
http://prntscr.com/7riqfl

As you're scrolling through the forums, it's really difficult to skim the number of likes a post has. I believe it has to do with the bolding/weight of the font type in the box as it contrasts with the big, bright heart next to it. It's too overwhelming for the eye.

http://prntscr.com/7riqtl -- Here's what it looks like without the weight. 

I recommend we turn off the font weight for this particular box. Is that possible?

**Comment by rsyvarth** [comment]
This has been implemented and is on the live site.
