### ISSUE TITLE
LocalStorage Data includes Private Email Addresses

### ISSUE THREAD

**Issue by Draco18s** [DuxterInc/trendy-community#210]
I'm not even a web security expert and I *know* that this shouldn't happen.

Given that I can, in no way through normal use of the site access a user's registered email address I should not be able to extract it from the local storage.  There is literally NO reason my browser should even be AWARE of that information.

Here's the data stored relating to my own account:

"tags":{"id":215,"name":"owner_group_8","system":true}],"comments":[],"likes":[],"user":{"id":16273,"email":"draco18s@gmail.com","username":"Draco18s","photo":"28f983239df37b367e8c06182dd9ee02b6ad5944874082d9fef36dd4b749a3a4u16273.gif","cover":"","title":{"name":"Defense Council","badge":"Sunder.png"},"groups_id":8,"comment_count":3238,"twitter_id":"","twitch_id":"","youtube_id":"","new_notifications":0,"lang":"","created_at":"2011-11-14 03:50:00","updated_at":"2015-07-14 04:29:49","suspension":"0000-00-00 00:00:00","deleted_at":null,"last_active":"2015-07-14 04:29:49","last_notif_check":"2015-07-14 04:07:35","users_group":{"id":8,"name":"Defense Council","is_admin":false,"is_mod":false}},"liked":false,"commented":false,"commentable":false,"likeable":true},{"id":52107,"user_id":16273,"public":false,"pinned":false,"source":"user","source_content_id":"1136137","type":"forumPost","created_at":"2015-07-14 04:20:37","updated_at":"2015-07-14 04:20:37","deleted_at":null,"lang":"en","site":"all","content":{"article_title":"Best way to follow up on job app?","article_id":121200},"links":{"self":"https://dd2.duxapi.com/feed/entries/52107"},"pivot":{"tag_id":380,"content_id":52107}

**Comment by adamlieb** [comment]
Check again. Made SOME changes that cleaned up some but not all of this.

**Comment by Draco18s** [comment]
Awesome, that one's fixed.
