### ISSUE TITLE
Forum awards 2 Influence Points / Day

### ISSUE THREAD

**Issue by Draco18s** [DuxterInc/trendy-community#211]
I mentioned this in #209 but it appears to not be a fluke, as I was awarded two more influence today as well so I thought I'd make this its own issue.

Both Influence points are granted simultaneously and both cause a "congrats!" popup that must be closed (one after the other).

![](http://s13.postimg.org/l2nwjrgnr/influence.png)

**Comment by adamlieb** [comment]
Same issue. I'll close as a duplicate.
