### ISSUE TITLE
Image URL Wrapped Paths

### ISSUE THREAD

**Issue by Draco18s** [DuxterInc/trendy-community#212]
Or whatever the hell the site does.

In any case, this is absurd:

https://images.dungeondefenders.com/https://images.dungeondefenders.com/https://images.dungeondefenders.com/https://images.dungeondefenders.com/https://images.dungeondefenders.com/https://images.dungeondefenders.com/https://images.dungeondefenders.com/https://images.dungeondefenders.com/https://images.dungeondefenders.com/https://images.dungeondefenders.com/https://images.dungeondefenders.com/https://images.dungeondefenders.com/https://images.dungeondefenders.com/https://images.dungeondefenders.com/https://images.dungeondefenders.com/https://lh6.googleusercontent.com/FefXhca0EL7abuxL44zk4PEQ4Ze46SEL7Xs6XTpXVIjSV3yRRbd0y6fvdQNVHuKdtgSOi6j5tf-RPhT98yYQXG-TljqtsjSG45CfrgJM0XlPwmAOtR53J5QW56d0ydBGSO-nFBs

That's *15* instances of the re-hosting!

That URL was pulled directly from the Wipeaggedeon blog post.

**Comment by adamlieb** [comment]
Happens each time you edit your post for some reason. This post was edited 14 times it seems :smile: going down as a non critical bug

**Comment by adamlieb** [comment]
This is fixed. Editing posts no longer prepends the URL again. This won't fix old edited posts with long image paths, but no new ones will suffer this.

**Comment by Draco18s** [comment]
Awesome!
