### ISSUE TITLE
Launcher Issues

### ISSUE THREAD

**Issue by CatFerry** [DuxterInc/trendy-community#213]
1) When you first open up the launcher, the carousel often doesn't work and you only see the first image stationary. If you close it out and reopen it, sometimes it'll work. Should work at first launch, though.

2) Manager allows you to add a 5th image, but the launcher only accommodates four:
![image](https://cloud.githubusercontent.com/assets/9061598/9042833/52111532-39df-11e5-8e38-a92c889bb3c9.png)
Remove ability to add 5th image and link.

**Comment by adamlieb** [comment]
Please let me know if 1) is still happening. I don't think it was ever reproducable.

2) has been resolved by removing them.
