### ISSUE TITLE
Icons on the All Notification page have wrong margins

### ISSUE THREAD

**Issue by Draco18s** [DuxterInc/trendy-community#215]
![iron](https://cloud.githubusercontent.com/assets/1750680/9253528/38b1c2a6-41ac-11e5-9e42-da3e3a487865.png)

Margin-right is 10 pixels, the other three are 5 pixels.  This makes the circular border lopsided.

**Comment by adamlieb** [comment]
Done and on live.

**Comment by Draco18s** [comment]
Awesome.
