### ISSUE TITLE
Non-square user icons and the notification dropdown

### ISSUE THREAD

**Issue by Draco18s** [DuxterInc/trendy-community#217]
In all other places, non-square user icons are squashed to make them square.

In the notifications dropdown, however, they retain their original aspect ratio.
![squashed](https://cloud.githubusercontent.com/assets/1750680/9321367/61ecbef2-4533-11e5-8331-b78aa89ac9e2.png)

**Comment by adamlieb** [comment]
Also fixed!

**Comment by Draco18s** [comment]
Awesome.
I'll have trouble verifying as there aren't many people with a non-square icon.  But I trust that it is :D
