### ISSUE TITLE
odd floating picture on page 2 of the snapshooter contest blog.

### ISSUE THREAD

**Issue by bradpettigrew** [DuxterInc/trendy-community#218]
![weird thing](https://cloud.githubusercontent.com/assets/9043584/9342422/8b6b2188-45c9-11e5-8a13-29be731132ef.jpg)

please compare the following 2 pages of comments from the blog post. 

https://www.dungeondefenders.com/2/topic/123206/snapshooter-contest?page=1
https://www.dungeondefenders.com/2/topic/123206/snapshooter-contest?page=2

**Comment by rsyvarth** [comment]
This issue should now be resolved globally on the site. (If there are any existing corrupted posts remaining they will still be broken but new posts  won't have this issue)
