### ISSUE TITLE
slight changes to assets 

### ISSUE THREAD

**Issue by bradpettigrew** [DuxterInc/trendy-community#221]
![testbg](https://cloud.githubusercontent.com/assets/9043584/10087081/e545eeee-62df-11e5-9fec-46bc71cd3133.jpg)

![9-24 redlines2](https://cloud.githubusercontent.com/assets/9043584/10087246/c84c7d16-62e0-11e5-9bde-1494c32792f9.jpg)

![fixed pets block background](https://cloud.githubusercontent.com/assets/9043584/10087079/e5431980-62df-11e5-8cc0-567b340effd0.jpg)

hey guys a few little changes here ... 2 assets I'd like to swap out. 1 of which might need to have the way it's sized on the page changed slightly

https://drive.google.com/drive/folders/0BytMt-v3T_nBT2ZfNXB1Rnc3LWs

above is a drive with the assets

**Comment by rsyvarth** [comment]
This should be live on production.
