### ISSUE TITLE
PS4 Forums Category

### ISSUE THREAD

**Issue by CatFerry** [DuxterInc/trendy-community#222]
Add the PS4 category to the forums here
![image](https://cloud.githubusercontent.com/assets/9061598/10113297/c64efb62-63b0-11e5-8263-7dfeba072923.png)
call it "PS4 FEEDBACK" and use the same Apprentice image as the SUGGESTIONS category. For the icon, use the PS4 icon you can download here: https://drive.google.com/file/d/0BytMt-v3T_nBc0Jhbm9jamo5V3c/view?pli=1

**Comment by rsyvarth** [comment]
Done
