### ISSUE TITLE
Add "Loot Testing Feedback" Forum

### ISSUE THREAD

**Issue by CatFerry** [DuxterInc/trendy-community#228]
Hey guys, we'd like to add another section to the forums today if possible. We'd like it to go in the top right next to General Discussion where Game Feedback currently is and move everything else down. Use the standard memo image used in Game Feedback and Patch Notes. Is that possible? Similar to when we added the ps4 feedback forum section and call it "LOOT TESTING FEEDBACK"

Use the Monk image which is currently also used under Website Feedback image.

**Comment by rsyvarth** [comment]
Done and on production
