### ISSUE TITLE
New subforum "Streams and Events"; new hierarchy

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#232]
We need a new subforum called "Streams and Events." 

After the removal of Defense Council Suggestions and Loot Testing Feedback, this will be the new forum hierarchy:

Defense Council General Discussion
General Discussion
PS4 Feedback and Discussion
Streams and Events
Game Feedback
Tech Support & Bug Reports
Suggestions
Defender's Lounge
Website Feedback
Trendy Only
Archive

**Comment by timh** [comment]
Hi @iamisom. These changes have been made. However, I notice a category named 'Patch Notes' that wasn't in your list. Where should that go?
