### ISSUE TITLE
Private Messages link you to DDE instead of DD2's part of the forums

### ISSUE THREAD

**Issue by j3272945** [DuxterInc/trendy-community#242]
When the forums send you a message about receiving a new message its URL sends you to Dungeon Defenders Eternity.

```
Hello Name,

User has sent you a new personal message!

Read Now (https://www.dungeondefenders.com/eternity/messages/148266)
```

If this can be updated so it points to

https://dungeondefenders.com/2/messages/148266

Then our community will be still on DD2's part of the forums instead of being forced to DDE's part of the website.

**Comment by rsyvarth** [comment]
It was previously setup so that it would link to the same site that the message was sent from. I have updated the email to force a link to DD2. This change is on production.
