### ISSUE TITLE
Permanent Bans should not remove a player's post history

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#243]
Can we get rid of that functionality please? The desired result is that:

1)  A mod "bans" a user.
2)  That user does not have access to the site anymore, but the user's posts are still there.

**Comment by adamlieb** [comment]
Will investigate. The main problem is it orphans content without a creator, which can break things.

**Comment by iamisom** [comment]
I don't believe banning a player should delete them from the forums. It should just disable their posting privileges.

**Comment by AnthonyKinson** [comment]
I'm currently doing a quick patch that will suspend users indefinitely when you "ban" them. This will keep their accounts live, and their content present in the community, but will prevent them from logging into the site.

I will close out this issue once it has gone live.

**Comment by AnthonyKinson** [comment]
This is now live. let us know if you have any questions or problems.
