### ISSUE TITLE
Reverse ban/deletion of flashertjeuh

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#246]
User "flashertjeuh" was accidentally banned, which deleted all of his posts and removed him from the forums. Can we reverse this? (PS:  This is why we want the ban post deletion removed.)

**Comment by AnthonyKinson** [comment]
I'm reversing this for you now. I will update once I am complete.

**Comment by AnthonyKinson** [comment]
i believe this user is now fully restored. including notifications / settings / likes / tracks and forum activity. https://dungeondefenders.com/2/user/145559

If we have missed anything please let us know.
