### ISSUE TITLE
New Forum Hierarchy

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#248]
Community wants more visibility on Game Feedback.

- Defense Council General Discussion
- General Discussion
- PS4 Feedback and Discussion
- Game Feedback
- Streams and Events
- Tech Support & Bug Reports
- Suggestions
- Defender's Lounge
- Patch Notes
- Website Feedback
- Archive

**Comment by AnthonyKinson** [comment]
This has been updated for you.

![](http://ant.zone/100216161629.png)

**Comment by iamisom** [comment]
Thank you!
