### ISSUE TITLE
Notification window blocking mobile users from accessing website

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#251]
https://www.reddit.com/r/dungeondefenders/comments/45a9d2/forums_mobile_problems/

**Comment by iamisom** [comment]
This one is pretty high priority. Any status update on this?

**Comment by rsyvarth** [comment]
I believe this is the same issue that was affecting the DD2 site on iOS. I have applied the same fix to DDE and DD1 and pushed to production. I am closing this issue now but if the issue persists please reopen.
