### ISSUE TITLE
Thread title character count changed to 80 characters

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#255]
People are making thread titles that take up 3-4 lines. We'd like the character count changed to 80 characters to keep thread titles at 2 lines max.

**Comment by adamlieb** [comment]
Yes. We can get this changed next week.

**Comment by iamisom** [comment]
Thanks, Adam. :D

**Comment by iamisom** [comment]
How's that coming along? Still getting some crazy long thread titles.

**Comment by adamlieb** [comment]
Will be live by EOW

**Comment by iamisom** [comment]
Thanks!

**Comment by rsyvarth** [comment]
This limit has been implemented and deployed
