### ISSUE TITLE
Change influence vote title on Front Page/Launcher

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#262]
http://prntscr.com/am57bb

We need the Influence Vote title to say "New Hero: Round One"

**Comment by adamlieb** [comment]
Instead of "active initiative?"

**Comment by iamisom** [comment]
Yes, please.

**Comment by rsyvarth** [comment]
Changed on the production website - updating launcher now

**Comment by iamisom** [comment]
Hey. Hey you. Thank you. :dancer: <---- Apparently github has its own emotes?

**Comment by rsyvarth** [comment]
Launcher update has been deployed. Should be good to go!

Closing, feel free to reopen if I borked something.
