### ISSUE TITLE
Remove Influence Point refunding (for now)

### ISSUE THREAD

**Issue by iamisom** [DuxterInc/trendy-community#263]
We need to remove Influence Point refunds if you lose. We need to pull the points out of the economy for the tournament vote we're doing.

**Comment by adamlieb** [comment]
Rob will investigate. Should be doable.

**Comment by rsyvarth** [comment]
We will now take everyone's points! (this has been deployed)

**Comment by iamisom** [comment]
Is this for every vote, or just the one we put out in March? Phil and I spoke, and we'd like this to be the norm for the system. Just want to make sure the current vote that ends on Friday won't refund points and that any future votes won't refund points.

**Comment by rsyvarth** [comment]
All votes act this way from now on

**Comment by iamisom** [comment]
Fantastic. Thanks!
